### ISSUE TITLE
Ghidra treating stack pointer as variable around function calls in top layer

### ISSUE THREAD

**Issue by ch00f** [GaryOderNichts/ghidra-hc11-lang#2]
I'm not sure if this is a library issue or a Ghidra issue (I'm new to Ghidra).

The first function call in my code is a LDS to set the stack pointer.

```
void main(void)


{
  short *sVar1;
  byte bVar1;
  byte bVar2;
  
  sVar1 = (short *)LoadStack(0xff);
  sVar1[-1] = 0xc006;
  Boot_Config();
  sVar1[-1] = 0xc009;
  Long_Delay();`
```

As you can see, it's displaying the program counter getting pushed to the stack before the function calls. Everywhere else in the code (like inside Boot_Config for example), this pushing of the program counter is obfuscated as part of the function call.

Interestingly, if I define a function on the next instruction after the LDS command, I get the expected behavior:
```
void main(void)

{
  byte bVar1;
  byte bVar2;
  
  Boot_Config();
  Long_Delay();
```

It's not a major issue since it only affects the main function where LDS is called, but is there a way to tell Ghidra that LDS deals with the stack pointer and doesn't need to be explicitly mentioned in the decompiled code?

**Comment by GaryOderNichts** [comment]
This seems to be something ghidra does if the stack pointer is being set in the current scope. I don't think I can avoid this in the sleigh spec.
