### ISSUE TITLE
Thanks and a typo

### ISSUE THREAD

**Issue by rimwall** [GaryOderNichts/ghidra-hc11-lang#3]
Hi, 

I'm no expert on Ghidra processors, but I thought you might like to know there seems to be a small typo on line 92 of the slaspec file:

Current line 92:
`oprx8_Y:		imm8,IX  is imm8 & IX { addr:2 = IY + zext(imm8:1); export addr; }`

Updated line 92:
`oprx8_Y:		imm8,IY  is imm8 & IY { addr:2 = IY + zext(imm8:1); export addr; }`

Thanks!

**Comment by GaryOderNichts** [comment]
Good catch!
