### ISSUE TITLE
One more; I think the manual has an error...?

### ISSUE THREAD

**Issue by rimwall** [GaryOderNichts/ghidra-hc11-lang#4]
For the MUL instruction, the processor manual says the C flag is "set if bit 7 of the result (ACCB bit 7) is set". But the result is in ACCD, not ACCB. So, I think this change is probably required to line 1663...?

Current:

```
:MUL                       is Prebyte=0 & op8=0x3D {
	D = zext(A) * zext(B);
	$(C) = B[7,1];
}
```

Updated:

```
:MUL                       is Prebyte=0 & op8=0x3D {
	D = zext(A) * zext(B);
	$(C) = D[7,1];
}
```

**Comment by GaryOderNichts** [comment]
The two 8-bit A and B accumulators can be used as a single 16-bit accumulator called the D register. They still share the same data though.
`$(C) = B[7,1];` and `$(C) = D[7,1];` is equivalent and leads to the same result.
![image](https://github.com/user-attachments/assets/19c9ae3d-fe27-454a-8bb2-56bccb60aa37)

**Comment by rimwall** [comment]
Ah, yes, you're quite correct. Apologies and thanks.

By the way, I am putting together a HC16 language but have hit a problem. If you're interested, more info here: https://github.com/NationalSecurityAgency/ghidra/discussions/6871

Thanks!
